
version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: protejo_spring_angular
    ports:
      - "5432:5432"  # - local:docker

    volumes: # aonde ficara os dados apos derrubar o container
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data: